### PR TITLE
Switch from HTMLRunner to Firebox

### PR DESCRIPTION
**Pull request by Gozala**
While this looks like two liner it is a very significant change. I've created [firebox](https://github.com/gozala/firebox) project branch that integrates ideas from HTMLRunner, while providing additional benefits:

1. Hacking on firebox does not require building firefox, just edit & reload. This will make it a lot easier for everyone to hack on the runtime.
2. Now `npm install` sep will take care of installing everything, all you would need to do is run `npm start` to start hacking.
3. Firebox does not needs to rebuild .zip file on reload as it actually loads code from the directory where app code is developed.
4. Firebox can load apps from the web, I'm able to run firefox.html by running `open -n -a FirefoxNightly --args -app $(pwd)/node_modules/firebox/application.ini http://localhost/\~gozala/Projects/firefox.html/manifest.webapp`.
5. Firebox does not bound to any specific APP and you could run different applications with it.

That being said, I don't know what would be an equivalent of `open` command so current `npm start` will only work on mac, but it should be possible to fix that.

### CODE REVIEW

**Comment by paulrouget** [comment]
Wow. This is really awesome!!! Preferences are loaded at startup, and it appears to just work. Damn.

**Comment by paulrouget** [comment]
I see you use a `<browser>`. I'm worried about that. We really want to keep the XUL code minimal. A browser comes with many many things. Why couldn't you keep the iframe?

Also - can you confirm that the docshell used to load the iframe is a content docshell and not a chrome docshell?

**Comment by paulrouget** [comment]
Also, ideally we want to use a `<html:iframe>` in the top level chrome docshell. I didn't manage to make it transparent, so I used a `<xul:iframe>`, but I don't think it's hard to fix.

**Comment by paulrouget** [comment]
Done there: https://github.com/mozilla/browser.html

**Comment by Gozala** [comment]
> I see you use a <browser>. I'm worried about that. We really want to keep the XUL code minimal. A browser comes with many many things. Why couldn't you keep the iframe?

We could use xul:iframe, it works just as fine. Only reason I end up using `browser` is because I had it in firebox in the past & I did not realized it was havier than xul:iframe.

> Also - can you confirm that the docshell used to load the iframe is a content docshell and not a chrome docshell?

Documents are content privileged, do you mean adding some sort of assertion in the code to threw if it is not ?

**Comment by Gozala** [comment]
> Also, ideally we want to use a <html:iframe> in the top level chrome docshell. I didn't manage to make it transparent, so I used a <xul:iframe>, but I don't think it's hard to fix.

I did run into the same problem when attempting to use html iframe, in addition html iframe was inheriting privileges from the parent document & did not found a way to make it content type. I'm happy to use html iframe if there is a way!

**Pull request closed without merging**
